### ISSUE TITLE
move to Scala 2.12

### ISSUE THREAD

**Issue by SethTisue** [playframework/play-scala-rest-api-example#79]
currently `build.sbt` has:

```
// This must be set to 2.11.11 because Gatling does not run on 2.12.2
scalaVersion in ThisBuild := "2.11.11"
```

but according to @manohar9999, Gatling may actually work with 2.12? has it been tried recently? (regardless, we should at least have an open issue on this, so here one is)

I tried cloning the repo, changing `scalaVersion` to 2.12.2 and got:

```text
[error] Modules were resolved with conflicting cross-version suffixes in {file:/Users/tisue/play-scala-rest-api-example/}root:
[error]    com.typesafe.akka:akka-actor _2.12, _2.11
[error]    org.scala-lang.modules:scala-xml _2.12, _2.11
[error]    org.scala-lang.modules:scala-java8-compat _2.12, _2.11
[error]    org.scala-lang.modules:scala-parser-combinators _2.12, _2.11
[error]    com.typesafe.akka:akka-slf4j _2.12, _2.11
```

it appears from https://github.com/gatling/gatling/issues/3179 that there may be WIP on a 2.12-friendly build of Gatling, but may not a release yet? I'd dig deeper, but I thought I'd check first if y'all already know more about this than I do

this is of interest to the Scala team and the HPE Fortify integration effort, since all of the Play example repos are good QA fodder (as suggested by @wsargent)

**Comment by SethTisue** [comment]
@gmethvin any interest in this?

**Comment by gmethvin** [comment]
I don't know anything about the gatling issue in particular but I can make an attempt to do the 2.12 upgrade here when I get a chance.

**Comment by legopiraat** [comment]
I recently tried to use gatling with scala 2.12 and this is an error i got just to provide some information:

```
Caused by: java.lang.NoSuchMethodError: scala.reflect.internal.settings.MutableSettings$SettingValue.$init$(Lscala/reflect/internal/settings/MutableSettings$SettingValue;)V
        at scala.tools.nsc.settings.MutableSettings$Setting.<init>(MutableSettings.scala:363)

```

**Comment by marcospereira** [comment]
Apparently, Gatling support for 2.12 is scheduled for late 2017 (or early 2018):

https://github.com/gatling/gatling/issues/3099#issuecomment-312854842

What we can do here is have a sub-project for the Gatling code and use Scala 2.11 for it.

**Comment by sebastianharko** [comment]
@SethTisue @marcospereira @gmethvin any news on this ?

**Comment by marcospereira** [comment]
Hi @sebastianharko, this is now using Scala 2.12.4:

https://github.com/playframework/play-scala-rest-api-example/blob/256311603b1d929d738290f3914e368d10698682/build.sbt#L5

With a small hack to make it compatible with multiple versions of Gatling:

https://github.com/playframework/play-scala-rest-api-example/blob/256311603b1d929d738290f3914e368d10698682/build.sbt#L9-L12

I think we can close this issue now. :-)
